### ISSUE TITLE
Automate sparse-checkout configuration

### ISSUE THREAD

**Issue by eemeli** [mozilla-l10n/firefox-l10n-source#6]
The Firefox repo is Big, and we only need about 1% of it, so we use a sparse checkout. If (when...) new locale directories are added, this configuration needs to be updated to match. We should be able to automate this by reading the paths from the `l10n.toml` files.

**Comment by flodolo** [comment]
> We should be able to automate this by reading the paths from the l10n.toml files.

Scenario: a new path is added to a TOML file in the code repository. 

At this point, automation will open a new PR in this repo, updating the local TOML file. But the sparse checkout already happened to trigger this PR, so it won't include the new path.

Personally, I think it would be OK that the new content will only be included in the next PR.

I've been playing around with trying to generate the list of folders in the `prepare` job, then passing it as output to the sparse checkout, but I haven't been very successful 😞 (tried various array formats, even JSON).

**Comment by eemeli** [comment]
That's roughly what I had in mind, with two qualifiers:
1. The local file is a YAML file, `update.yml`.
2. After merging the PR with the updated sparse checkout config, a manually triggered or timed update run can add them to the in-progress update PR rather than needing to wait for a separate one.

**Comment by flodolo** [comment]
> 1. The local file is a YAML file, update.yml.

When I say "local TOML file"; I mean browser/l10n.toml. You need to read paths from those, don't you?

As for point 2: I'm not sure you can, at least with the current logic? The first step for the workflow is to clone `main`, then push it to the `update` branch.

**Comment by flodolo** [comment]
In case it's helpful, this is as far as I got (`list.txt` is a file with one folder per line).

I think I tried all possible combinations (bash arrays, JSON, quoted or non-quoted) without success, even if the log of the action looks the same as the current action.

```YAML
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.folders.outputs.folders }}
    steps:
      - name: Checkout l10n:main
        uses: actions/checkout@v4
      - name: List folders
        id: folders
        run: |
          folders=$(cat list.txt)
          output="folders="
          for f in $folders; do
              output+="$f "
          done;
          echo $output >> "$GITHUB_OUTPUT"
          echo $output
  update:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout firefox:master
        uses: actions/checkout@v4
        with:
          repository: mozilla/gecko-dev
          ref: master
          path: firefox
          sparse-checkout: |
            ${{ needs.prepare.outputs.folders }}
      - name: Check content folder
        run: |
          find . -type f
        working-directory: firefox
```
